<a href="https://colab.research.google.com/github/Suki-gpu/ML-journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np


In [9]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5 6]
(6,)
1
6
int64


In [10]:
ar = np.array([2.2,3.5,9.6])
print(ar)
print(ar.size)
print(ar.ndim)
print(ar.shape)
print(ar.dtype)


[2.2 3.5 9.6]
3
1
(3,)
float64


In [15]:
b = np.array([[1,2],[3,4]])
print(b)
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)


[[1 2]
 [3 4]]
4
2
(2, 2)
int64


In [17]:
np.arange(5,200,15)

array([  5,  20,  35,  50,  65,  80,  95, 110, 125, 140, 155, 170, 185])

In [21]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])